### ISSUE TITLE
Method Query of Container type does not exist in NuGet package

### ISSUE THREAD

**Issue by thyvini** [bcarruthers/garnet#14]
When I tried to use c.Query() on my game, the IDE said that the method does not exist, and the project don't compile.
I've solved this by cloning the repository and referencing it on my project.
I think that it would be great to have a minor release to include this on NuGet.

**Comment by bcarruthers** [comment]
I went ahead and posted a new package with the latest changes, including querying. Let me know if you have any trouble!
